MCLOUD-7387: Add MFTF documentation for AWS S3
magento/magento2-functional-testing-framework pull request #809
Opened 2020-12-07 19:02 UTC by shiftedreality

### Description

### Fixed Issues (if relevant)

1. magento/magento2-functional-testing-framework#<issue_number>: Issue title
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/verification tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)
 - [ ] Changes to Framework doesn't have backward incompatible changes for tests or have related Pull Request with fixes to tests

2020-12-07 19:57 UTC, dshevtsov requested changes

2020-12-07 19:57 UTC, dshevtsov commented on docs/configuration.md
> +The remote storage driver, to enable AWS S3 use `aws-s3`
```suggestion
The remote storage driver. To enable AWS S3, use `aws-s3`.
```

2020-12-07 19:57 UTC, dshevtsov commented on docs/configuration.md
> +The optional secret ket to access S3 bucket.
```suggestion
The optional secret key to access S3 bucket.
```

2020-12-09 15:18 UTC, jilu1 commented
@magento import pr to magento-commerce/magento2-functional-testing-framework

2020-12-09 15:19 UTC, magento-engcom-team commented
@jilu1 the pull request successfully imported.

2020-12-14 15:21 UTC, jilu1 commented
@magento import pr to magento-commerce/magento2-functional-testing-framework

2020-12-14 15:22 UTC, magento-engcom-team commented
@jilu1, an error occurred during the Pull Request import.

2020-12-14 15:23 UTC, jilu1 commented
@magento import code to magento-commerce/magento2-functional-testing-framework

2020-12-14 15:24 UTC, magento-engcom-team commented
@jilu1, an error occurred during the Pull Request import.

2020-12-14 15:53 UTC, jilu1 commented
Manually created internal pr https://github.com/magento-commerce/magento2-functional-testing-framework/pull/15 with updated content

2020-12-14 16:54 UTC, merged